### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/distributed-wikipedia-mirror#10]
Currently there is no search available in the IPFS version.

Turkish version has 521k titles with redirects (not sure right now how many without) which weight total of 13MiB (3MiB gzip compressed). Chalenge would be writing fuzzy search over them in ways that:

 - don't bright the browser to its knees
 - saves bandwidth (it is one time download if local ipfs is running but still downloading it right away for every one is a lot), so probably download gzip version.
 - is fast; uncompressing the gzip version every time to do the search is wastefull but also english wiki has 13M articles.
 - supports unicode

This might be a place to investigate some precalculated data structure that could be stored in IPFS to improve the search, speed and bandwidth wise. If the data structure is sharded in IPFS there should be a button to download whole search index.

**Comment by flyingzumwalt** [comment]
@Kubuxu did this using https://github.com/magik6k/distributed-wiki-search
