### ISSUE TITLE
Wikipedia Mirror for Afghanistan

### ISSUE THREAD

**Issue by kelson42** [ipfs/distributed-wikipedia-mirror#100]
Following https://twitter.com/AlexHinojo/status/1426902378020843522

**Comment by kelson42** [comment]
It seems there is no Wikipedia in Dari, see https://en.wikipedia.org/wiki/Dari. But it might be worth to make the one in Farsi instead. ZIM file is available at https://download.kiwix.org/zim/wikipedia_fa_all.zim.

Wikipedia ZIM file in Pasto is available at https://download.kiwix.org/zim/wikipedia_ps_all.zim.

**Comment by arky** [comment]
We never got enough momentum with Dari(prs) contributions in most open source community projects.

**Comment by lidel** [comment]
Sadly the build is broken again (confirmed that it is not specific to `pa`, latest `my` is also broken, most likely other ones too).
I am running `fa` now, but it will take a bit more time to confirm.

Filled  https://github.com/ipfs/distributed-wikipedia-mirror/issues/101 (my) and https://github.com/ipfs/distributed-wikipedia-mirror/issues/102 (pa) with more details. 

Note: I am unable to sink more time into fixing ZIM unpacking and publishing. 
It took too long last time (weeks!), engineering overhead is not sustainable imo.

:point_right: [We really need to figure out web-based reader and use original ZIMs](https://github.com/ipfs/distributed-wikipedia-mirror/issues/42#issuecomment-766980230)
 (remove the need for unpacking and manual customization)

**Comment by lidel** [comment]
That being said, I was able to build `fa` from `wikipedia_fa_all_maxi_2021-06.zim` and here we were lucky: it seems to work out of the box:
- https://dweb.link/ipfs/bafybeicpnshmz7lhp5vcowscty4v4br33cjv22nhhqestavb2mww6zbswm/wiki/
- https://cf-ipfs.com/ipfs/bafybeicpnshmz7lhp5vcowscty4v4br33cjv22nhhqestavb2mww6zbswm/wiki/

**Comment by lidel** [comment]
DNSLink at https://fa.wikipedia-on-ipfs.org/wiki/ should be working.

@arky @kelson42 it is ok to share the above link, or encourage people to install Brave  and open  `ipfs://bafybeicpnshmz7lhp5vcowscty4v4br33cjv22nhhqestavb2mww6zbswm`.

(The PR  https://github.com/ipfs/distributed-wikipedia-mirror/pull/103 will be merged when I get a confirmation that is pinned outside my machine.)

**Comment by arky** [comment]
Yes, Please \o/  

Kudos @lidel @kelson42
