### ISSUE TITLE
Publish IPNS entry for turkish wikipedia snapshot

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#11]
Eventually wikimedia might generate their own IPNS entry. In the meantime, we need to publish one of our one.

- [x] Generate a keypair for the turkish wikipedia snapshot (@whyrusleeping)
- [x] Publish the current snapshot's hash using that keypair. The snapshot hash is QmQP99yW82xNKPxXLroxj1rMYMGF6Grwjj2o4svsdmGh7S (@whyrusleeping)
- [x] Set up some means to keep the IPNS hash resolvable (@lgierth)

blocks https://github.com/ipfs/blog/pull/93

**Comment by whyrusleeping** [comment]
I figure we can use the ipfs keystore to create a key, then have a cronjob (for now) that republishes it. Will be important to get pingdom resolving that particular entry

**Comment by flyingzumwalt** [comment]
This is one of the remaining blockers for publishing the blog post. (we need to include the IPNS hashes in the post)

@whyrusleeping do you want to do this? Do we need @lgierth to do it?

**Comment by flyingzumwalt** [comment]
@whyrusleeping generated this IPNS hash: QmVH1VzGBydSfmNG7rmdDjAeBZ71UVeEahVbNpFQtwZK8W
