### ISSUE TITLE
Minify output files

### ISSUE THREAD

**Issue by ljmf00** [ipfs/distributed-wikipedia-mirror#117]
To reduce the space usage significantly, the web pages should be minified as well as Javascript and CSS content.

**Comment by kelson42** [comment]
Probably a ticket for openzim/mwoffliner

**Comment by ljmf00** [comment]
> Probably a ticket for openzim/mwoffliner

Moved https://github.com/openzim/mwoffliner/issues/1586

**Comment by ljmf00** [comment]
Reopened according to https://github.com/openzim/mwoffliner/issues/1586#issuecomment-1024349632 . Feel free to close it, but desires a rationale attached.

**Comment by lidel** [comment]
I think this is not worth it, given small size reduction when compared to reusing ZIM without unpacking it.
We should instead invest time into using compressed ZIMs directly: #42
