### ISSUE TITLE
Publish IPNS entry for english wikipedia snapshot

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#12]
Eventually wikimedia might generate their own IPNS entry. In the meantime, we need to publish one of our one.

- [x] Generate a keypair for the english wikipedia snapshot
   - https://ipfs.io/ipns/QmdJiuMWp2FxyaerfLrtdLF6Nr1EWpL7dPAxA9oKSPYYgV
- [ ] Publish the current snapshot's hash using that keypair. _(when we have loaded the english snapshot onto ipfs we will point this ipns entry to point to the snapshot's hash)_

**Comment by Ivshti** [comment]
@flyingzumwalt what's the status on English wikipedia? Can you clear this up a bit? You say you're waiting for "that hash" - I presume it's currently being uploaded?

**Comment by flyingzumwalt** [comment]
The IPNS entry (which we can update to point to the hash of the most recent snapshot) will be https://ipfs.io/ipns/QmdJiuMWp2FxyaerfLrtdLF6Nr1EWpL7dPAxA9oKSPYYgV
When the english snapshot is ready, we will update that IPNS entry to point to it.

**Comment by flyingzumwalt** [comment]
snapshot of _simple english_ wikipedia (much smaller than the main english wikipedia): https://ipfs.io/ipfs/QmU2TE8ym8rBAMwzaanZ3SbVtBJY4R7oX2uN1fca4JAnrD/wiki/Billy_Graham.html

**Comment by flyingzumwalt** [comment]
The IPNS entry, which will resolve to the most current IPFS snapshot whenever we put out new english snapshots, is published. Tracking the work to actually publish the snapshot itself in https://github.com/ipfs/distributed-wikipedia-mirror/issues/31
