### ISSUE TITLE
How to request a page be deleted?

### ISSUE THREAD

**Issue by noraft75** [ipfs/distributed-wikipedia-mirror#121]
Hi, I'm not a coder, but I was wondering if I'm in the right place to have a Wikipedia article deleted from https://yamm.finance/

The article in question was deleted from Wikipedia years ago, but this yamm.finance mirror still displays it. I wasn't sure who else to contact.

Thank you

**Comment by rasos** [comment]
Somebody made a copy of the Wikipedia using the software of this project and the content in ZIM format (https://library.kiwix.org) in 2016. You would need to contact the owner of the site yamm.finance, which may be tricky, as contact details are hidden when doing a whois query.
