### ISSUE TITLE
Broken image on the repo's README.md page

### ISSUE THREAD

**Issue by ilyaigpetrov** [ipfs/distributed-wikipedia-mirror#138]
I have tested the page directly and via VPN, in Chrome and Firefox -- in all cases the image is broken.

![ipfs-wiki-mirror](https://github.com/ipfs/distributed-wikipedia-mirror/assets/1090811/dde17654-fdbe-4945-b2ed-57424f72e0c9)

**Comment by alzinging** [comment]
lets get ready ... anyone wqanna fork AR and become an overnight billionaire?




Sent with Proton Mail secure email.
