### ISSUE TITLE
Add Arabic and Kurdish snapshots

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#14]
Add Snapshots of http://ar.wikipedia.org and http://ku.wikipedia.org

The IPNS entries for these snapshots will be  (we can update these links to point to the hash of the most recent snapshot) :
* Arabic (ar.wikipedia.org): https://ipfs.io/ipns/QmNayrUbrwPYQ9hKk9YevbebUDrrfgQboi2BfsuKmuZEjC
* Kurdish (ku.wikipedia.org): https://ipfs.io/ipns/QmakP2ZAzEEUpfK6ng2tKHCM56cdEDXDBX2aV5EtPvqpHm

When the corresponding snapshots are ready, we will update that IPNS entries to point to the snapshots. We will also announce the links to those snapshots in comments on this issue and on the ipfs blog.

**Comment by jbenet** [comment]
i got some requests on IRC for this, too

**Comment by flyingzumwalt** [comment]
@Kubuxu can we kick off these snapshots once the new snapshotting process is settled?

**Comment by Kubuxu** [comment]
I wanted to do the on the new host but it seems to be late.

**Comment by Kubuxu** [comment]
Arabic one is similar in size to Turkish which means it will take a while for it to extract and add on this host (12h or so if everything goes well).

**Comment by flyingzumwalt** [comment]
Update: The Arabic dump from kiwix is giving us trouble. see #26 if you want to help or to learn more.

@Kubuxu when you have a hash for the Kurdish snapshot published and pinned please add the hash to https://github.com/ipfs/distributed-wikipedia-mirror/blob/master/snapshot-hashes.md in a PR.

**Comment by flyingzumwalt** [comment]
Update: we have published a kurdish snapshot at https://ipfs.io/ipns/QmakP2ZAzEEUpfK6ng2tKHCM56cdEDXDBX2aV5EtPvqpHm

The corresponding IPNS entry hasn't been updated yet, but the direct IPFS link works.

Closing this issue. We will  track work for the arabic snapshot in #30
