### ISSUE TITLE
Upload source logo with layers

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#16]
upload the source file for the logo here: https://github.com/ipfs/distributed-wikipedia-mirror/issues/13#issuecomment-299398452

(need to modify it to insert in the new snapshots)

add it to this repo in /assets/.

**Comment by jbenet** [comment]
Here it is, with png, jpg, pxm, and psd versions: https://ipfs.io/ipfs/Qmb4KKaZyRK1hgx7FUutiwUfA3ZM2iwzC6QuqD5jYEDeBj

**Comment by jbenet** [comment]
![](https://ipfs.io/ipfs/Qmb4KKaZyRK1hgx7FUutiwUfA3ZM2iwzC6QuqD5jYEDeBj/wikipedia-on-ipfs.png)

**Comment by jbenet** [comment]
I changed the logo-- we can't use the last wikipedia logo as that one is trademarked and this does not qualify within their branding guidelines. See:
- https://wikimediafoundation.org/wiki/Trademark_policy
- https://wikimediafoundation.org/wiki/Visual_identity_guidelines
- https://wikimediafoundation.org/wiki/Wikimedia_trademarks


I tried it without:

![wikipedia-on-ipfs-blank](https://cloud.githubusercontent.com/assets/138401/25770790/ad56e774-31f3-11e7-8847-204b8214178e.png)


But i dont like it-- I used the very original logo, which i believe is fine to use this way, as i believe it is not trademarked, and not under any of the guidelines i could find from wikipedia:

![](https://ipfs.io/ipfs/Qmb4KKaZyRK1hgx7FUutiwUfA3ZM2iwzC6QuqD5jYEDeBj/wikipedia-on-ipfs.png)

**Comment by flyingzumwalt** [comment]
Thank you. Added to the PR in this commit https://github.com/ipfs/distributed-wikipedia-mirror/pull/15/commits/9be3ac29721efe57da1a55fcd718a3b3e1e22182
