### ISSUE TITLE
Insert custom footer into snapshots

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#17]
Make a `body.js`  file in this repo that inserts our footer instead of the original social media links. When we build wikipedia snapshots we will replace the original body.js with this new body.js so the footer includes a clear statement about who generated the snapshots. (see https://github.com/ipfs/distributed-wikipedia/issues/13)

Add the new file to #16

**Comment by Kubuxu** [comment]
Is having this content in articles OK: `This article is issued from Vikipedi - version of the 1/11/2017. The text is available under the Creative Commons Attribution/Share Alike but additional terms may apply for the media files.`?

If not we have to rewrite the articles either way.

**Comment by flyingzumwalt** [comment]
Yes. It's ok to have that content in the articles as long as we have the additional info in our footer immediately below it saying who generated and disseminated the snapshot.

**Comment by VictorBjelkholm** [comment]
Added body.js that will add our footer. This file will need to have the variables inside it replaced before adding to IPFS.

Added a demo as well, to make sure it works. If you add that whole directory to IPFS and go to `/out/A/Anasayfa.html`, the correct footer should be rendered.

```
➜  distributed-wikipedia git:(feat/footer) tree demo 
demo
├── out
│   ├── -
│   │   └── j
│   │       └── body.js
│   └── A
│       └── Anasayfa.html
└── wikipedia-on-ipfs.png
```

Looks like this:

![image](https://cloud.githubusercontent.com/assets/459764/25771955/71face04-325f-11e7-8466-6c747f89c7e1.png)

**Comment by flyingzumwalt** [comment]
Thanks @VictorBjelkholm! I added the "This snapshot was generated and distributed by..." line back into the body.js. Now we're good to go!
