### ISSUE TITLE
Write a script that modifies ZIM dumps to include info about how they were generated

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#18]
1. Replace `out/-/j/body.js` with the `/scripts/body.js` from this repo
2. In that copy of body.js, replace these placeholders with the relevant values
    * {{SNAPSHOT_DATE}} -- date that this snapshot is being generated
    * {{IPNS_HASH}} - IPNS hash for this version of wikipedia (probably corresponds to the language code. ie. tr.wikipedia.org probably has its own ipns hash)
3. Copy `/assets/wikipedia-on-ipfs.png` into the root of the snapshot
4. Copy `/assets/wikipedia-on-ipfs-small-flat-cropped-offset-min.png` to `/out/I/s/Wikipedia-logo-v2-200px-transparent.png` in the snapshot

When you're done writing this script, please
* add the script to this repo
* Update the instructions in the repo's README.md to include the new step of running this script.

**Comment by flyingzumwalt** [comment]
I made step 4 a bit simpler

**Comment by flyingzumwalt** [comment]
Uploaded a new, renamed cropped logo file. It's now `/assets/wikipedia-on-ipfs-small-flat-cropped-min.png`

**Comment by flyingzumwalt** [comment]
Final update: you need `/assets/wikipedia-on-ipfs-small-flat-cropped-offset-min.png`  -- need the version with an offset

**Comment by flyingzumwalt** [comment]
@Kubuxu  how do you run this script? I need to update teh instructions in the readme.md and the blog post.

**Comment by Kubuxu** [comment]
I have the wiki hash in files API under `root` So lets say QmAAA... is my hash:
```sh
ipfs files cp /ipfs/QmAAA... /root
bash ./execute-changes.sh
```

But a lot of it is Turkish wiki specific. I haven't got to generalizing it yet.

**Comment by flyingzumwalt** [comment]
Which hash is `QmAAA...` ? The IPNS hash?

It looks like the script takes arguments https://github.com/ipfs/distributed-wikipedia-mirror/blob/master/execute-changes.sh#L10-L11

**Comment by Kubuxu** [comment]
It is IPFS hash of your added wiki. It does the changes after you add it.

**Comment by Kubuxu** [comment]
This is internal function, it doesn't take any arguments as I will be modifying this script (right now it is heavy WIP) you might want to reference given commit.

**Comment by Kubuxu** [comment]
Just pushed, hopefully last update to it.

**Comment by flyingzumwalt** [comment]
I've put sample instructions in https://github.com/ipfs/distributed-wikipedia-mirror/pull/20 but I need you to update/clarify.

**Comment by flyingzumwalt** [comment]
Thanks @kubuxu.
