### ISSUE TITLE
links should be exactly the same as wikipedia

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributed-wikipedia-mirror#2]
links should be exactly the same as wikipedia
- pages have “.html” at the end, can we get no “.html”? (with directories + index.htmk or whatever)
- i want the links to be the same so people can just change a prefix somewhere and have everything else just work
- are media links the same as they are on wikipedia.org?

**Comment by Kubuxu** [comment]
> pages have “.html” at the end, can we get no “.html”? (with directories + index.html or whatever)
This is possible as a step after adding into IPFS but will result in a trailing slash after the article name (wikipedia won't accept it back: https://en.wikipedia.org/wiki/DNA/)

> are media links the same as they are on wikipedia.org?

Quite similar but wikimeida does sharding in fs (wikimedia uploads is backed by filesystem and kiwix/zim files skip this step) So links are:
 - zim: /I/m/Tower_185_during_construction_phase_on_a_sunny_afternoon-Edit.jpg
 - wikimedia: https://upload.wikimedia.org/wikipedia/commons/f/f7/Tower_185_during_construction_phase_on_a_sunny_afternoon-Edit.jpg

Where `f/f7` is randomised/hashed.

**Comment by jbenet** [comment]
- going to distributed version is easy and obvious. (right now it's not)
- going back to wikipedia is way easier than now
- so let's do it

**Comment by jbenet** [comment]
> Quite similar

can we get them to be _exactly the same_?

**Comment by lgierth** [comment]
> can we get them to be exactly the same?

Yes but this will take significant work on how the dumps are created

**Comment by jbenet** [comment]
what's "significant work"? should we leave it for later?

i want to make sure people can take existing wikipedia links and apply a trivial transform manually (eg changing the domain) and have it all just work.

**Comment by lgierth** [comment]
For a quick fix at least on ipfs.io, we can apply a redirect that appends the .html suffix.

> what's "significant work"? should we leave it for later?

@Kubuxu will know more, but I think it's either a) making the dumps closer to the original, or 2) adding links within ipfs.

Or maybe it's as simple as writing the files out without the .html suffix in the first place? I think it's okay to just not have that suffix?

**Comment by Kubuxu** [comment]
> can we get them to be exactly the same?

Not right now, it would require:
1. knowing how sharding is done
2. rendering pages ourselves (or rewriting all current pages to those).
3. moving the files to shards

It is a lot of work t odo.

> we can apply a redirect that appends the .html suffix.

This would mean that it wouldn't work on local gateways. Non-uniform UX is bad.

@jbenet is trailing `/` ok?

**Comment by JanZerebecki** [comment]
> wikimedia: https://upload.wikimedia.org/wikipedia/commons/f/f7/Tower_185_during_construction_phase_on_a_sunny_afternoon-Edit.jpg
> Where f/f7 is randomised/hashed.

I think it is the first byte, a slash and the first 2 bytes of the md5sum string of the file name, didn't check in the configuration nor code and this may vary by installation.
