### ISSUE TITLE
Add OS-native installers to ipfs station

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#22]
IPFS Station is an electron app that installs and runs IPFS for you. We want to make it easier to install station by adding a package builder to IPFS station that generates installers for Win, Mac and Linux. This will make it possible for everyday users to run their own copy of IPFS and access it locally without using the command line.

More info and instructions in the ipfs station repository here: https://github.com/ipfs/station/issues/508

**Comment by lidel** [comment]
IPFS Station was renamed to IPFS Desktop:

- https://github.com/ipfs-shipyard/ipfs-desktop/#ipfs-desktop
