### ISSUE TITLE
Make the ipfs web extension more secure

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#23]
We've created a web extension that lets you install and run IPFS in your web browser. We have held off on releasing it because we need to make it more secure. If you are a javascript developer and you want to help us make it secure so that people can use the extension, please got to https://github.com/VictorBjelkholm/js-ipfs-in-the-browser/issues/ and take a look at https://github.com/VictorBjelkholm/js-ipfs-in-the-browser/issues/1

**Comment by lidel** [comment]
@flyingzumwalt  I feel this can be closed, as it was superseded by moving [ipfs-companion](https://github.com/ipfs-shipyard/ipfs-companion) to IPFS org, yes?

**Comment by lidel** [comment]
Browser extension lives at: https://github.com/ipfs-shipyard/ipfs-companion#install :-)
