### ISSUE TITLE
Turkish Mirror Doesn't have Page about the referendum

### ISSUE THREAD

**Issue by simplymathematics** [ipfs/distributed-wikipedia-mirror#24]
The Turkish referendum was the inciting incident that led Erdogan to block wikipedia. That is because it mentioned how he stole the election. It would be excellent if you could update that single page if at all possible before this goes **live**

**Comment by lgierth** [comment]
Where do we get that page?

**Comment by lgierth** [comment]
This has already gone live ~18 hours ago

**Comment by meyerscr** [comment]
https://en.wikipedia.org/wiki/Turkish_constitutional_referendum,_201

https://tr.wikipedia.org/wiki/2017_T%C3%BCrkiye_anayasa_de%C4%9Fi%C5%9Fikli%C4%9Fi_referandumu

**Comment by lgierth** [comment]
Mh I wonder why that's not part of the dump. We can try patching it in.

**Comment by Kubuxu** [comment]
It is because it was created at the end of April, the Kiwix dump was created at the mid or April.

https://en.wikipedia.org/w/index.php?title=Turkish_constitutional_referendum,_2017&action=history

**Comment by VictorBjelkholm** [comment]
@Kubuxu seems the turkish version of the page was first made on January 21, 2017 though, https://tr.wikipedia.org/w/index.php?title=2017_T%C3%BCrkiye_anayasa_de%C4%9Fi%C5%9Fikli%C4%9Fi_referandumu&offset=20170128113837&limit=500&action=history

**Comment by Kubuxu** [comment]
Hmm, interesting.

**Comment by meyerscr** [comment]
The most important part is about the controversy surrounding the referendum, which only came after the votes were 'counted' on April 16th. The ipns hash has the information, but the URL does not.

**Comment by flyingzumwalt** [comment]
Sounds like we need to talk to kiwix about their dumps - see if there are more complete or more current versions available.

**Comment by flyingzumwalt** [comment]
Update: we are still trying to get a more recent dump from kiwix. The turkish snapshot is definitely outdated -- the styling was updated for all of the new dumps but hasn't been updated for the turkish dump.

**Comment by meyerscr** [comment]
Oh man. I hope I don't have to pin a whole new snapshot. It took 72 hours of grueling downloads.

**Comment by flyingzumwalt** [comment]
_Note: this is off topic. If you want to discuss bandwidth needs and improvements, please redirect the conversation to https://discuss.ipfs.io_
We have a lot of bandwidth optimizations coming. In the long run we intend for IPFS to be at least as fast as HTTP and in many cases faster. We are all super motivated to work on this. This is part of what motivated us to create https://github.com/ipfs/test-lab -- it lets us spin up test networks and test performance in various scenarios.

**Comment by JanZerebecki** [comment]
It seems not only does it not contain all articles that existed as of the date 2017-04, also some articles are multiple month older version than existed when other articles where last edited that made it.

**Comment by kelson42** [comment]
The solution here seems indeed to be pretty simple: download last version of the ZIM file. Here is the permalink, a new version has been published a few days ago: download.kiwix.org/zim/wikipedia_tr_all.zim. So far I have seen last time I checked, you were using a ZIM file from January 2017.

**Comment by Kubuxu** [comment]
Was the file updated? I was downloading it from there 1.5months ago.

**Comment by kelson42** [comment]
@Kubuxu Yes this is a permalink and a new version has been published a few days ago.

**Comment by VictorBjelkholm** [comment]
> The solution here seems indeed to be pretty simple: download last version of the ZIM file

Not sure if it's that simple. Even the ZIM file from January 2017 doesn't seem to include all the pages, or we are not including all pages from it, as noted in the above comments.

**Comment by kelson42** [comment]
@VictorBjelkholm I do not follow you. Can you be more specific please? This ticket is about missing https://tr.wikipedia.org/wiki/2017_T%C3%BCrkiye_anayasa_de%C4%9Fi%C5%9Fikli%C4%9Fi_referandumu. Yourself has identified that it was created the 21 January and the ZIM file used has been published the January 13th. Case closed!?

**Comment by flyingzumwalt** [comment]
Let's pull down the new ZIM and see if it's there. Fingers crossed...

**Comment by Kubuxu** [comment]
Doing it right now.

**Comment by Kubuxu** [comment]
Extraction took: 1m 30s
ipfs add took: 4m

I am using the old search graph. I might ask @Magik6k to create script in this repo for rebuilding the graph.

**Comment by Kubuxu** [comment]
The article exists in new mirror: https://ipfs.io/ipfs/QmeuuJnfJoXfWnJPj4wcNe2sZTXqrAzVKQ7ThK56aG5dNw/wiki/2017_T%C3%BCrkiye_anayasa_de%C4%9Fi%C5%9Fikli%C4%9Fi_referandumu.html

**Comment by kelson42** [comment]
Ticket could probably be closed.
