### ISSUE TITLE
Citation links broken

### ISSUE THREAD

**Issue by mateon1** [ipfs/distributed-wikipedia-mirror#25]
Assuming we are on page `/ipfs/QmRoot/wiki/SomePage.html`, when we try to click a citation link, instead of scrolling the page with a `#cite_note-xx` anchor, it tries to load `/ipfs/QmRoot/wiki/SomePage#cite_note-xx`, which fails, as `SomePage` does not exist.

Related to #2

**Comment by Kubuxu** [comment]
It seems to be problem with how Kiwix renders the dumps, solution would be to https://github.com/ipfs/distributed-wikipedia-mirror/issues/9

**Comment by lidel** [comment]
I believe this is solved.
If not, feel free to reopen with a link to a page with the problem.
