### ISSUE TITLE
Kiwix Data Urls, md5 sums, created dates

### ISSUE THREAD

**Issue by b5** [ipfs/distributed-wikipedia-mirror#27]
After a chat with @flyingzumwalt, part of this project may need to programmatically check for updates to kiwix downloads. This seemed like a logical starting point:

https://gist.github.com/b5/2d1002ba04f1dcfc03cce9ab4e520b4f

Feel free to close this :)

**Comment by flyingzumwalt** [comment]
:+1: super useful. I'm glad you were able to scrape this info.
