### ISSUE TITLE
Turkish IPFS mirror doesn't work with localhost redirect: core/serve error

### ISSUE THREAD

**Issue by JayBrown** [ipfs/distributed-wikipedia-mirror#28]
When I deactivate my localhost redirect script, the turkish WP mirror loads fine (both ipfs snapshot & ipns current version) via the ipfs.io gateway. After enabling the userscript, the redirect to localhost works, i.e. the address has the correct hash etc., but browser & console print error messages:

```
00:35:07.573 ERROR core/serve: ipfs cat /ipns/QmVH1VzGBydSfmNG7rmdDjAeBZ71UVeEahVbNpFQtwZK8W/wiki/Anasayfa.html: no link named "wiki" under QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX gateway_handler.go:525

00:37:51.368 ERROR core/serve: ipfs cat /ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/Anasayfa.html: no link named "wiki" under QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX gateway_handler.go:525
```

Anyone know what's producing the error? Other ipfs/ipns address redirects seem to work fine.

EDIT: direct input of localhost addresses produces the same errors.

**Comment by lgierth** [comment]
You'll need to install go-ipfs 0.4.9-rc2 from https://dist.ipfs.io -- the final 0.4.9 release is hopefully gonna happen over the weekend.

**Comment by JayBrown** [comment]
Oh, I can wait. Was just worried I had messed something up on my end. Thanks for the info.

**Comment by JayBrown** [comment]
Works great with 0.4.9.
