### ISSUE TITLE
Add Arabic snapshot

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#30]
blocked by #26 , replaces #14

Add Snapshot of http://ar.wikipedia.org 

The IPNS entry for this snapshots will be  (we can update these links to point to the hash of the most recent snapshot) :
* Arabic (ar.wikipedia.org): <del>https://ipfs.io/ipns/QmNayrUbrwPYQ9hKk9YevbebUDrrfgQboi2BfsuKmuZEjC</del>

When the corresponding snapshot is ready, we will update that IPNS entry to point to the snapshot. We will also announce the link to thjat snapshots in comments on this issue and on the ipfs blog.

**Comment by flyingzumwalt** [comment]
This is blocked by #26 -- there's something wrong with the ZIM file from kiwix. If anyone wants to help, please jump in.

**Comment by llopv** [comment]
Can this issue be closed now?

**Comment by flyingzumwalt** [comment]
No. We still haven't gotten a working arabic ZIM file from Kiwix

**Comment by lidel** [comment]
Done: https://ar.wikipedia-on-ipfs.org :sparkles:
