### ISSUE TITLE
Provide recommendations for using InterPlanetary Test Lab to generate wikipedia snapshots

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#32]
@FrankPetrilli in order to follow the data control plan described [here](https://github.com/ipfs/distributed-wikipedia-mirror/issues/8#issuecomment-300958190) we need a way to spin up workers based on a configuration (or docker file) and then use those workers to 
* download data from a specified HTTP source
* unpack the data and write it to IPFS
* run a script (from this repo) that modifies the data (using IPFS files API)
* pin the resulting data somewhere
* return the hash of the result

This overlaps with the kind of stuff that we do with InterPlanetary Test Lab. How hard would it be to set this up?

**Comment by lidel** [comment]
Continued in #58
