### ISSUE TITLE
wrapper script for building snapshots

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#35]
As a person who wants to build snapshots, I want to build a snapshot for a specific language by

* cloning this repo
* running a single script with a simple command (just providing the language code)

Completion state:

This repository provides a script that takes one required argument: the language code of the snapshot you want to build.
Based on that argument and the info in this repo, it 
* pulls from kiwix
* unpacks the dump
* modifies the dump
* writes the result to ipfs
* reports the resulting hash

**Comment by Kubuxu** [comment]
Dependencies we need for this to happen:
- rust or built `extract_zim`
- ipfs daemon running

Would those dependencies be ok with you @flyingzumwalt ?

**Comment by lidel** [comment]
I believe this was closed by #77. One can now build the latest snapshot via


```console
$ ./mirrorzim.sh --languagecode=cu --wikitype=wikipedia
```
