### ISSUE TITLE
spec: worker for building snapshots

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#36]
design a worker that uses the script from #35 to 

1. uses the script from #35 to 
   - download data from a specified HTTP source
   - unpack the data and write it to IPFS
   - run a script (from this repo) that modifies the data (using IPFS files API)
   - pin the resulting data somewhere
2.  return the hash of the result
3. (maybe) submit a PR to https://github.com/ipfs/distributed-wikipedia-mirror with the new hash

Optional: 

Make the workers follow a queue.

**Comment by lidel** [comment]
Continued in  https://github.com/ipfs/distributed-wikipedia-mirror/issues/58
