### ISSUE TITLE
index.html in the `/wiki` directory

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributed-wikipedia-mirror#4]
we should add an "index.html" in the `/wiki` directory that just redirects browser to `/wiki/<Main>` (in that language)

**Comment by Kubuxu** [comment]
I wouldn't do straight redirect but give it a big link plus prepare space for search. It could be also page that explains how this wikipedia can be backed up, downloaded and used locally.

**Comment by jbenet** [comment]
ok sgtn

**Comment by lgierth** [comment]
Let's go with a redirect until we have that intro page, I think it's not worth blocking on it

**Comment by flyingzumwalt** [comment]
this is done.
