### ISSUE TITLE
read & write

### ISSUE THREAD

**Issue by joeblew99** [ipfs/distributed-wikipedia-mirror#45]
I am interested in IPFS and its applicability  for offline editing and then merging.
Basically think google docs.

This code base can do just that.
https://github.com/nickbradley/p2pwiki/blob/master/Specs.md

**Comment by lgierth** [comment]
You'll find CRDTs on js-ipfs interesting: https://ipfs.io/blog/30-js-ipfs-crdts/

(Thanks for the link to p2pwiki, interesting)

**Comment by joeblew99** [comment]
thanks @diasdavid 

They changed the link, so here it is for others:
https://ipfs.io/blog/30-js-ipfs-crdts.md

Will be kicking these tires thats for sure :)

**Comment by Kubuxu** [comment]
Hmm, it should have been fixed. Change of the link was a mistake.
