### ISSUE TITLE
Any updates? News? etc?

### ISSUE THREAD

**Issue by mkg20001** [ipfs/distributed-wikipedia-mirror#47]
Is this still actively maintained? Is there any roadmap? When will the mirror be read-write?

**Comment by burritofridays** [comment]
Also curious to know progress, I'm looking for interesting ideas to make using IPFS a daily occurrence. 

If we are simply hosting a copy of wikipedia then surely its easier to just have one node pull, shre their hash and everyone else wanting to support pin it into their local node?

**Comment by lidel** [comment]
Continued in  https://github.com/ipfs/distributed-wikipedia-mirror/issues/58
