### ISSUE TITLE
Schedule updating every 6 months/1 year?

### ISSUE THREAD

**Issue by superusercode** [ipfs/distributed-wikipedia-mirror#49]
If this isn't going to be updated often due to the size, there should at least be a schedule of sorts so it can be seen as maintained one way or another. I doubt Wikimedia will start updating it themselves if they see it isn't being updated as it is.

**Comment by superusercode** [comment]
@Kubuxu I assume you are the maintainer?

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/distributed-wikipedia-mirror/issues/58
