### ISSUE TITLE
ipns link broken

### ISSUE THREAD

**Issue by sixcorners** [ipfs/distributed-wikipedia-mirror#52]
https://ipfs.io/ipns/QmdJiuMWp2FxyaerfLrtdLF6Nr1EWpL7dPAxA9oKSPYYgV/wiki/ doesn't work anymore.

**Comment by VictorBjelkholm** [comment]
@lgierth @Kubuxu you remember what host the IPNS record was published from? Might have to double-check it's still running...

**Comment by jbshirk** [comment]
None of these IPNS addresses resolve as of today.

**Comment by lgierth** [comment]
IIRC the only that ever resolved was for tr.wikipedia -- it broke at some point and nobody repaired it :( I have the private key backed up.

**Comment by lgierth** [comment]
This was phrased a bit unclearly -- we were using the [ipns-pub tool](https://github.com/whyrusleeping/ipns-pub) to continuously publish that tr.wikipedia IPNS key. The setup was a bit adhoc and scrappy, and eventually broke.
