### ISSUE TITLE
Removing an old and outdated article

### ISSUE THREAD

**Issue by ivanshen** [ipfs/distributed-wikipedia-mirror#55]
There is an [article](https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Antony_Cheng.html) that is old and outdated, and I am wondering how can I take it down?

**Comment by MatthewSteeples** [comment]
The contents of the article will only change when a new shapshot is generated and published. If it's something that you want to help out with then you can have a look at the instructions in the README file

**Comment by lidel** [comment]
This will be "fixed" when we update english in #61
