### ISSUE TITLE
Missing ipfs files root?

### ISSUE THREAD

**Issue by maris205** [ipfs/distributed-wikipedia-mirror#56]
I use a small zim file: http://download.kiwix.org/zim/wikipedia_ace_all.zim

I follows the README.md
step 1-step4 are all right,
but In "Step 5: Add mirror info and search bar to the snapshot"
when using ./execute-changes.sh
it shows  error "Missing ipfs files root"

**Comment by maris205** [comment]
I read the execute-changes.sh
It seems that I should run
./execute-changes.sh /root/out

but there is still an error：
Error: no link named "head.js" under QmTT5kHY3RHfuQT5FXCM6Ntq5Nq4bgJ7vDU9VonbftES5W

**Comment by lidel** [comment]
A lot changed since 2019. The error reported here is fixed in #77, but `ace` fails due to missing canonical link – filled https://github.com/ipfs/distributed-wikipedia-mirror/issues/81 to track that
