### ISSUE TITLE
About the Contents Retrieve and Errors Corrections

### ISSUE THREAD

**Issue by hbscreatives** [ipfs/distributed-wikipedia-mirror#57]
Hello, 
How to update new info of the Wikipedia contents. Currently IPFS contents article was not updated. Please help us how to update the articles. IPFS articles have too old and wrong.

**Comment by lidel** [comment]
- Manual steps were updated in #77 –  README should be way closer to truth now.
- We track  updating of  `tr` in #60  and `en` in #61
