### ISSUE TITLE
instructions for adding new snapshots

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributed-wikipedia-mirror#7]
would be great to have a doc with instructions for adding new snapshots

**Comment by jbenet** [comment]
Ideally automated as much as possible. (Add scripts to this repo as needed)

**Comment by flyingzumwalt** [comment]
Basic version of the process @kubuxu and @dignifiedquire are using:

1. Download ZIM format snapshot of wikipedia from http://wiki.kiwix.org/wiki/Content_in_all_languages
2. Unpack it using https://github.com/dignifiedquire/zim/commit/a283151105ab4c1905d7f5cb56fb8eb2a854ad67
3. Add all data on directory sharding enabled node (`ipfs config --json ‘Experimental.ShardingEnabled’ true`) using `ipfs add -w -r --raw-leaves $upacked_wiki`.
4. Save the last hash of that output. It is the hash of wikipedia on IPFS.

**Comment by flyingzumwalt** [comment]
Current instructions are in the readme at https://github.com/ipfs/distributed-wikipedia-mirror#how-to-add-new-wikipedia-snapshots-to-ipfs

This process will evolve. We will update the documentation accordingly as things change.
