### ISSUE TITLE
Add Chinese Version distributed wikipedia mirror.

### ISSUE THREAD

**Issue by FledgeXu** [ipfs/distributed-wikipedia-mirror#74]
Thanks for all of maintainers, you did an excellent job for promoting spread of human knowledge.
And I'm here to ask could you add a Chinese version Wikipedia mirror on IPFS?
China, like Turkey, had interfered and blocked Wikipedia for years (since [2004](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E5%A4%A7%E9%99%86%E5%AF%B9%E7%BB%B4%E5%9F%BA%E5%AA%92%E4%BD%93%E7%9A%84%E5%B0%81%E9%94%81)) and China also has one of the most tight internet censorship in World. Thus, If we can have a decentralized and distributed wikipedia in China, I trust it's a great opportunity to introduce IPFS and the feature of decentralized and anti-censorship web.

**Comment by lidel** [comment]
We def. want to have more languages, but the cost of creating a new snapshot is quite high right now. 

Need to  fix #73   or  https://github.com/ipfs/distributed-wikipedia-mirror/issues/42 to unblock this.

**Comment by FledgeXu** [comment]
Thanks for replaying. I'm looking for it.

**Comment by kelson42** [comment]
Really supportive for that one.

**Comment by FledgeXu** [comment]
For now, I deployed a mirror. 
CID: `bafybeierrdxblmthjga6wap3tpk53icgzb7owstz5gbd6qxcy3kspktymm`
IPNS: `k51qzi5uqu5dirl3inwnhrl6nicsaq9snlzg2aj7blt2komssvff4c9ln8tch3`
It's not an official mirror, so I will keep this issue open and wait for #42 to close.
Anyway, @lidel and @kelson42 Thanks for your help. 🎉
