### ISSUE TITLE
Remove fixRedirects fixup

### ISSUE THREAD

**Issue by lidel** [ipfs/distributed-wikipedia-mirror#86]
It should soon be fixed upstream in `zimdump` nightly, so we may shave off some time by removing the `find+grep+sed` hack from  https://github.com/ipfs/distributed-wikipedia-mirror/commit/11fe184edd597e5ff0d80edc52b01b9b77af1ebb

Ref. https://github.com/openzim/zim-tools/pull/225

**Comment by kelson42** [comment]
Indeed, latest nightly build shoudl have the fix https://download.openzim.org/nightly/2021-02-25/zim-tools_linux-x86_64-2021-02-25.tar.gz
